// <auto-generated />
using System;
using CreditSimulator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditSimulator.Api.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    [Migration("20260917213041_UnifiedDatabase")]
    partial class UnifiedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditSimulator.Api.Entities.CreditType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreditTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualInterestRate = 15.5m,
                            Description = "Préstamo de libre disponibilidad para viajes, vehículos, tecnología o consolidación de deudas.",
                            MaxAmount = 40000m,
                            MaxMonths = 60,
                            MinAmount = 500m,
                            MinMonths = 6,
                            Name = "Crédito de Consumo",
                            TypeCode = 1
                        },
                        new
                        {
                            Id = 2,
                            AnnualInterestRate = 9.5m,
                            Description = "Financiamiento de vivienda nueva, usada, construcción o remodelación con tasa preferencial.",
                            MaxAmount = 500000m,
                            MaxMonths = 300,
                            MinAmount = 10000m,
                            MinMonths = 12,
                            Name = "Crédito Hipotecario",
                            TypeCode = 2
                        },
                        new
                        {
                            Id = 3,
                            AnnualInterestRate = 8.0m,
                            Description = "Financia estudios de pregrado, posgrado, maestrías y diplomados dentro y fuera del país.",
                            MaxAmount = 80000m,
                            MaxMonths = 120,
                            MinAmount = 1000m,
                            MinMonths = 6,
                            Name = "Crédito Educativo",
                            TypeCode = 3
                        });
                });

            modelBuilder.Entity("CreditSimulator.Api.Entities.SimulationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreditTypeCode")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialMonthlyPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime>("SimulatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SimulationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
